import { Client, GatewayIntentBits, EmbedBuilder } from "discord.js";
import "dotenv/config";
import fs from "fs";
import path from "path";

const ADMIN_ID = "934670194096345118";

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

client.once("ready", () => {
  console.log(`✅ Logged in as ${client.user.tag}`);
});

// location of your data file
const filePath = path.join(process.cwd(), "accounts.json");

// ensure data structure exists
function loadData() {
  if (!fs.existsSync(filePath)) {
    const init = { normal: [], banned: [] };
    fs.writeFileSync(filePath, JSON.stringify(init, null, 2));
  }
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}
function saveData(data) {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

client.on("messageCreate", async (message) => {
  if (message.author.bot) return;
  const content = message.content.trim();
  const data = loadData();

  // ----------------------------------------------------
  // USER HELP COMMAND
  // ----------------------------------------------------
  if (content === "$help" || content === "$mcfa help") {
    const embed = new EmbedBuilder()
      .setColor("#00FFAA")
      .setTitle("🧭 LoxY Hub User Help")
      .setDescription(
        "Here are the commands you can use:\n\n" +
          "💠 **$mcfa gen** → Get a free MCFA account (everyone can use)\n" +
          "💠 **$mcfa banned** → Get a free *banned* Minecraft account\n" +
          "💠 **$stock** → See how many accounts are left\n" +
          "💠 **$help** → Show this help message"
      )
      .setFooter({ text: "LoxY Hub • Support your community ❤️" });
    return message.reply({ embeds: [embed] });
  }

  // ----------------------------------------------------
  // ADMIN HELP COMMAND
  // ----------------------------------------------------
  if (content === "$adminhelp") {
    if (message.author.id !== ADMIN_ID)
      return message.reply("🚫 Only admin can use this command.");

    const embed = new EmbedBuilder()
      .setColor("#ff9933")
      .setTitle("🛠 LoxY Hub Admin Help")
      .setDescription(
        "Admin only commands:\n\n" +
          "🔧 **$mcfa add email password** → Add normal account\n" +
          "🔧 **$mcfa add Minecraft_banned email password** → Add banned account\n" +
          "🗑 **$mcfa reset banned** → Reset all banned accounts\n" +
          "🗑 **$mcfa reset mcfa** → Reset all normal accounts"
      )
      .setFooter({ text: "Only ADMIN_ID can run these." });
    return message.reply({ embeds: [embed] });
  }

  // ----------------------------------------------------
  // STOCK SHOW
  // ----------------------------------------------------
  if (content === "$stock") {
    const total = data.normal.length;
    const banned = data.banned.length;
    const embed = new EmbedBuilder()
      .setColor("#0099ff")
      .setTitle("📦 LoxY Hub Stock")
      .setDescription(
        `🧮 **Normal accounts:** ${total}\n` +
          `🚫 **Banned accounts:** ${banned}\n\n` +
          "Use **$mcfa gen** or **$mcfa banned** to get one!"
      );
    return message.reply({ embeds: [embed] });
  }

  // ----------------------------------------------------
  // ANYONE: GENERATE NORMAL ACCOUNT
  // ----------------------------------------------------
  if (content === "$mcfa gen") {
    const account = data.normal.shift();
    if (!account)
      return message.reply("❌ No normal accounts available!");

    saveData(data);

    const embed = new EmbedBuilder()
      .setColor("#00FFAA")
      .setTitle("🎁 Your Free MCFA Account")
      .setDescription(
        `Hey **${message.author.username}**, here’s your account:\n\n` +
          `> 📧 **Email:** \`${account.email}\`\n` +
          `> 🔐 **Password:** \`${account.password}\`\n\n` +
          "Enjoy! Remember to keep it private and use responsibly."
      )
      .setFooter({ text: "Generated by LoxY Hub" });

    await message.author.send({ embeds: [embed] }).catch(() =>
      message.reply("📬 Couldn’t DM you — enable DMs!")
    );
    return message.reply("📩 Check your DMs for the account details!");
  }

  // ----------------------------------------------------
  // ANYONE: GENERATE BANNED ACCOUNT
  // ----------------------------------------------------
  if (content === "$mcfa banned") {
    const account = data.banned.shift();
    if (!account)
      return message.reply("❌ No banned accounts available!");
    saveData(data);

    const embed = new EmbedBuilder()
      .setColor("#ff5555")
      .setTitle("🎮 Banned Minecraft Account")
      .setDescription(
        `Hey **${message.author.username}**, here’s a banned account:\n\n` +
          `> 📧 **Email:** \`${account.email}\`\n` +
          `> 🔐 **Password:** \`${account.password}\`\n\n` +
          "These are for testing or practice only — expect them to be banned on official Minecraft servers."
      )
      .setFooter({ text: "Provided by LoxY Hub • use wisely" });

    await message.author.send({ embeds: [embed] }).catch(() =>
      message.reply("📬 Couldn’t DM you — enable DMs!")
    );
    return message.reply("📩 Check your DMs for the banned account!");
  }

  // ----------------------------------------------------
  // ADMIN: ADD NORMAL ACCOUNT
  // ----------------------------------------------------
  if (content.startsWith("$mcfa add ")) {
    if (message.author.id !== ADMIN_ID)
      return message.reply("🚫 Only admin can add accounts.");

    const args = content.split(" ");
    if (args.length < 4)
      return message.reply(
        "Usage: `$mcfa add email password` or `$mcfa add Minecraft_banned email password`"
      );

    // distinguish between normal and banned
    if (args[2].toLowerCase() === "minecraft_banned") {
      const email = args[3];
      const password = args[4];
      data.banned.push({ email, password });
      saveData(data);
      return message.reply(
        `✅ Added banned account: **${email}** to banned list.`
      );
    } else {
      const email = args[2];
      const password = args[3];
      data.normal.push({ email, password });
      saveData(data);
      return message.reply(`✅ Added normal account for **${email}**`);
    }
  }

  // ----------------------------------------------------
  // ADMIN: RESET LISTS
  // ----------------------------------------------------
  if (content === "$mcfa reset banned") {
    if (message.author.id !== ADMIN_ID)
      return message.reply("🚫 Only admin can reset banned accounts.");
    data.banned = [];
    saveData(data);
    return message.reply("🧹 All banned accounts cleared!");
  }

  if (content === "$mcfa reset mcfa") {
    if (message.author.id !== ADMIN_ID)
      return message.reply("🚫 Only admin can reset normal accounts.");
    data.normal = [];
    saveData(data);
    return message.reply("🧹 All normal accounts cleared!");
  }
});

client.login(process.env.TOKEN);